version: '2'
 
services:
  webapp:
    build:
      context:  .
      dockerfile: Dockerfile
    expose:
      - "8081"
 
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - webapp